language: python 
python: 
- "3.6"
- "3.3"
- "2.7"
env: 
- DJANGO=2.0 DB=postgres
before_install: 
- cd decide
install: 
- pip install -r ../requirements.txt
script: 
- python manage.py test
sudo: required
services:
- postgresql
addons:
  postgresql: "9.6"
global:
  - PGPORT=5432
before_script:
 - psql -c "create user decide with password 'decide'" 
 - psql -c "create database decide owner decide"
 - sudo python3 manage.py migrate
 - cp local_settings.travis.py local_settings.py
